openapi: 3.1.0
info:
  title: User Management API
  description: API specification for managing users in Zag Systems, providing endpoints for user creation, retrieval, update, and deletion.
  version: 1.0.0
servers:
  - url: 'http://localhost:8000/'
    description: Local development server

paths:
  /users:
    post:
      tags:
        - User Management
      summary: Create a new user
      operationId: createUser
      requestBody:
        description: Details of the new user to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreateDto'
            examples:
              example1:
                value:
                  userName: "JohnDoe"
                  password: "John12"
                  email: "john.doe@example.com"
                  fullName: "John Doe"
                  mobileNumber: "01234567890"
                  role: "USER"
                  gender: "MALE"  # Example for gender as string
                  status: "ACTIVE"  # Example for status as string
      responses:
        '200':
          description: User created successfully
          content:
            application/json:
              schema:
                type: string
                example: "User added successfully."
    get:
      tags:
        - User Management
      summary: Retrieve all users
      operationId: getAllUsers
      responses:
        '200':
          description: A list of all users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserResponseDto'

  /users/{id}:
    get:
      tags:
        - User Management
      summary: Retrieve user details by ID
      operationId: getUserById
      parameters:
        - name: id
          in: path
          required: true
          description: The unique ID of the user
          schema:
            type: integer
      responses:
        '200':
          description: User details retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponseDto'

    put:
      tags:
        - User Management
      summary: Update an existing user
      operationId: updateUser
      parameters:
        - name: id
          in: path
          required: true
          description: The unique ID of the user
          schema:
            type: integer
      requestBody:
        description: Updated details of the user
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserUpdateDto'
            examples:
              example1:
                value:
                  id: 1
                  userName: "JohnDoeUpdated"
                  email: "john.updated@example.com"
                  mobileNumber: "01234567891"
                  role: "ADMIN"
                  password: "John12New"
                  status: "INACTIVE"  # Updated status as string
      responses:
        '200':
          description: User updated successfully
          content:
            application/json:
              schema:
                type: string
                example: "User updated successfully."

  /users/{id}/updatePassword:
    put:
      tags:
        - User Management
      summary: Update password for a user
      operationId: updatePassword
      parameters:
        - name: id
          in: path
          required: true
          description: The unique ID of the user whose password is to be updated
          schema:
            type: integer
      requestBody:
        description: Request body for updating the password
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserUpdatePasswordDto'
            examples:
              example1:
                value:
                  id: 1
                  oldPassword: "John12"
                  newPassword: "John12New"
      responses:
        '200':
          description: Password updated successfully
          content:
            application/json:
              schema:
                type: string
                example: "Password updated successfully."

components:
  schemas:
    UserCreateDto:
      type: object
      required:
        - userName
        - password
        - email
        - fullName
        - mobileNumber
        - role
        - gender
        - status
      properties:
        userName:
          type: string
          description: The username of the user
          pattern: "^[A-Za-z]+$|^[A-Za-z]+\\d+$"
          example: "JohnDoe"
        password:
          type: string
          description: The password for the user
          minLength: 5
          maxLength: 10
          pattern: "^[A-Za-z]+\\d{2}$"
          example: "John12"
        email:
          type: string
          description: The email address of the user
          format: email
          example: "john.doe@example.com"
        fullName:
          type: string
          description: The full name of the user
          example: "John Doe"
        mobileNumber:
          type: string
          description: The mobile number of the user
          pattern: "^\\d{11}$"
          example: "01234567890"
        role:
          type: string
          description: The role assigned to the user
          example: "USER"
        gender:
          type: string
          description: The gender of the user
          example: "MALE"  # Gender as string, not enum
        status:
          type: string
          description: The status of the user account
          example: "ACTIVE"  # Status as string, not enum

    UserUpdateDto:
      type: object
      required:
        - id
      properties:
        userName:
          type: string
          description: The username of the user
          pattern: "^[A-Za-z]+$|^[A-Za-z]+\\d+$"
          example: "JohnDoeUpdated"
        email:
          type: string
          description: The email address of the user
          format: email
          example: "john.updated@example.com"
        mobileNumber:
          type: string
          description: The mobile number of the user
          pattern: "^\\d{11}$"
          example: "01234567891"
        role:
          type: string
          description: The role assigned to the user
          example: "ADMIN"
        password:
          type: string
          description: The password for the user
          minLength: 5
          maxLength: 10
          pattern: "^[A-Za-z]+\\d{2}$"
          example: "John12New"
        status:
          type: string
          description: The status of the user account
          example: "INACTIVE"  # Updated status as string

    UserUpdatePasswordDto:
      type: object
      required:
        - id
        - oldPassword
        - newPassword
      properties:
        oldPassword:
          type: string
          description: The current password of the user
          minLength: 5
          maxLength: 10
          example: "John12"
        newPassword:
          type: string
          description: The new password for the user
          minLength: 5
          maxLength: 10
          example: "John12New"

    UserResponseDto:
      type: object
      properties:
        id:
          type: integer
          description: The unique ID of the user
          example: 1
        userName:
          type: string
          description: The username of the user
          example: "JohnDoe"
        email:
          type: string
          description: The email address of the user
          format: email
          example: "john.doe@example.com"
        fullName:
          type: string
          description: The full name of the user
          example: "John Doe"
        mobileNumber:
          type: string
          description: The mobile number of the user
          example: "01234567890"
        role:
          type: string
          description: The role of the user
          example: "USER"
        gender:
          type: string
          description: The gender of the user
          example: "MALE"  # Gender as string
        status:
          type: string
          description: The account status of the user
          example: "ACTIVE" # Status as string
